JavaScript Errors
Throw, and Try...Catch...Finally
The try statement defines a code block to run (to try).
The catch statement defines a code block to handle any error.
The finally statement defines a code block to run regardless of the result.
The throw statement defines a custom error.
Errors Will Happen!
When executing JavaScript code, different errors can occur.
Errors can be coding errors made by the programmer, errors due to wrong input, and other unforeseeable things.
<body>
  <p id="gk"></p>
  <script>
    try{
        addalert("Welcome, kibria"); 
    }
    catch(er){
        document.getElementById("gk").innerHTML = er.message; 
    }
  </script>
</body>
addalert is not defined
***
JavaScript Throws Errors
When an error occurs, JavaScript will normally stop and generate an error message.
The technical term for this is: JavaScript will throw an exception (throw an error).
JavaScript will actually create an Error object with two properties: name and message.
The throw Statement
The throw statement allows you to create a custom error.
Technically you can throw an exception (throw an error).
The exception can be a JavaScript String, a Number, a Boolean or an Object:
throw "Too big";    // throw a text
throw 500;          // throw a number
If you use throw together with try and catch, you can control program flow and generate custom error messages.
***
Input Validation Example
This example examines input. If the value is wrong, an exception (err) is thrown.
The exception (err) is caught by the catch statement and a custom error message is displayed:
<body>
  <h2>Error Handling</h2>
  <p>Enter a number between 5 and 10</p>
  <input id="gki">
  <button onclick="myFunc()">Click Me</button>
  <p id="sr"></p>
  <script>
    function myFunc(){ 
      let inpt = document.getElementById("gki").value; 
      let result = document.getElementById("sr");

      try {
        if(inpt == "") throw "Empty"; 
        if(isNaN(inpt)) throw "Not a number"; 
        inpt = Number(inpt); 
        if(inpt < 5) throw "Too low"; 
        if(inpt > 10) throw "Too high"; 
      } 
      catch (err) {
        result.innerHTML = "Input is: "+err; 
      }
      finally{
        document.getElementById("gki").value = ""; 
      }
    }
  </script>
</body>
***
Range Error
A RangeError is thrown if you use a number that is outside the range of legal values.
For example: You cannot set the number of significant digits of a number to 500.
Example
let num = 1;
try {
  num.toPrecision(500);   // A number cannot have 500 significant digits
}
catch(err) {
  document.getElementById("demo").innerHTML = err.name;
}
***
Reference Error
A ReferenceError is thrown if you use (reference) a variable that has not been declared:
Example
let x = 5;
try {
  x = y + 1;   // y cannot be used (referenced)
}
catch(err) {
  document.getElementById("demo").innerHTML = err.name;
}
***
Syntax Error
A SyntaxError is thrown if you try to evaluate code with a syntax error.
Example
try {
  eval("alert('Hello)");   // Missing ' will produce an error
}
catch(err) {
  document.getElementById("demo").innerHTML = err.name;
}
***
Type Error
A TypeError is thrown if you use a value that is outside the range of expected types:
Example
let num = 1;
try {
  num.toUpperCase();   // You cannot convert a number to upper case
}
catch(err) {
  document.getElementById("demo").innerHTML = err.name;
}
***
URI (Uniform Resource Identifier) Error
A URIError is thrown if you use illegal characters in a URI function:
Example
try {
  decodeURI("%%%");   // You cannot URI decode percent signs
}
catch(err) {
  document.getElementById("demo").innerHTML = err.name;
}
***
